openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8800
tags:
  - name: auth
    description: Logs in a user.
paths:
  /api/auth/login:
    post:
      tags:
        - auth
      summary: Login an existing user
      description: Login into system
      operationId: login
      requestBody:
        description: Information login
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: The user's username
                  example: su
                password:
                  type: string
                  description: The user's password
                  example: 123
        required: true
      responses:
        200:
          description: "Login successful."
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      isAdmin:
                        type: boolean
        400:
          description: "Bad request."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.
        404:
          description: "User not found."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.
        403:
          description: "User is forbidden."
        401:
          description: "User is unauthorized."
  /api/auth/register:
    post:
      tags:
        - "auth"
      summary: "Register a new user."
      description: "This endpoint allows users to register new accounts."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "The user's username."
                email:
                  type: string
                  description: "The user's email address."
                password:
                  type: string
                  description: "The user's password."
      responses:
        201:
          description: "User has been created."
        400:
          description: "Bad request."
        500:
          description: "Internal server error."
  /api/hotels:
    get:
      tags:
        - "hotels"
      summary: Get all hotels
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: "Hotel A"
                  type: "Luxury"
                  city: "City A"
                  address: "Address A"
                  distance: "5 km"
                  photos: ["url1", "url2"]
                  title: "Hotel A Title"
                  desc: "Description of Hotel A"
                  rating: 4.5
                  rooms: ["Room1", "Room2"]
                  cheapestPrice: 150
                  featured: true

    post:
      tags:
        - "hotels"
      summary: Create a new hotel
      security:
        - cookieAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "The hotel's name."
                type:
                  type: string
                  description: "The hotel's type."
                city:
                  type: string
                  description: "The hotel's city."
                address:
                  type: string
                  description: "The hotel's address."
                distance:
                  type: string
                  description: "The hotel's distance from the city center."
                photos:
                  type: array
                  description: "The hotel's photos."
                title:
                  type: string
                  description: "The hotel's title."
                desc:
                  type: string
                  description: "The hotel's description."
                rating:
                  type: number
                  description: "The hotel's rating."
                rooms:
                  type: array
                  description: "The hotel's rooms."
                cheapestPrice:
                  type: number
                  description: "The hotel's cheapest price."
                featured:
                  type: boolean
                  description: "Whether the hotel is featured."
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 2
                name: "New Hotel"
                type: "Standard"
                city: "City B"
                address: "Address B"
                distance: "3 km"
                photos: ["url3", "url4"]
                title: "New Hotel Title"
                desc: "Description of New Hotel"
                rating: 4.0
                rooms: ["RoomA", "RoomB"]
                cheapestPrice: 120
                featured: false

  /api/hotels/{id}:
    get:
      tags:
        - "hotels"
      summary: Get a specific hotel by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the hotel
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: "Hotel A"
                type: "Luxury"
                city: "City A"
                address: "Address A"
                distance: "5 km"
                photos: ["url1", "url2"]
                title: "Hotel A Title"
                desc: "Description of Hotel A"
                rating: 4.5
                rooms: ["Room1", "Room2"]
                cheapestPrice: 150
                featured: true

    put:
      tags:
        - "hotels"
      summary: Update a specific hotel by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the hotel
          schema:
            type: string
      requestBody:
        content:
          application/json:
            example:
              name: "Updated Hotel"
              type: "Luxury"
              city: "City A"
              address: "Updated Address"
              distance: "5 km"
              photos: ["url1", "url2"]
              title: "Updated Hotel Title"
              desc: "Updated Description"
              rating: 4.8
              rooms: ["Room1", "Room2", "Room3"]
              cheapestPrice: 180
              featured: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: "Updated Hotel"
                type: "Luxury"
                city: "City A"
                address: "Updated Address"
                distance: "5 km"
                photos: ["url1", "url2"]
                title: "Updated Hotel Title"
                desc: "Updated Description"
                rating: 4.8
                rooms: ["Room1", "Room2", "Room3"]
                cheapestPrice: 180
                featured: true

    delete:
      tags:
        - "hotels"
      summary: Delete a specific hotel by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the hotel
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example: "Hotel with ID 1 has been deleted"

    post:
      tags:
        - "rooms"
      summary: Create a new room.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the room to be updated.
          schema:
            type: string
      requestBody:
        description: Updated room object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Room"

      responses:
        200:
          description: Successfully created room.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        400:
          description: Bad request.
        401:
          description: Unauthorized.

  /api/rooms/{id}/{hotelid}:
    delete:
      tags:
        - "rooms"
      summary: Delete a room by ID.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the room to be deleted.
          schema:
            type: string
        - in: path
          name: hotelid
          required: true
          description: The ID of the hotel from which the room should be deleted.
          schema:
            type: string
      responses:
        200:
          description: Room has been deleted.
        401:
          description: Unauthorized
        404:
          description: Room not found

  /api/rooms/{id}:
    put:
      tags:
        - "rooms"
      summary: Update a room by ID.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the room to be updated.
          schema:
            type: string
      requestBody:
        description: Updated room object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Room"
      responses:
        200:
          description: Successfully updated room.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        400:
          description: Bad request.
        401:
          description: Unauthorized
    get:
      tags:
        - "rooms"
      summary: Get a room by ID.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the room to be retrieved.
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved room.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
        401:
          description: Unauthorized
        404:
          description: Room not found
  /api/rooms:
    get:
      tags:
        - "rooms"
      summary: Get all rooms.
      operationId: getAllRooms
      responses:
        200:
          description: Successfully retrieved all rooms.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        401:
          description: Unauthorized
  /api/rooms/{id}/availability:
    put:
      tags:
        - "rooms"
      summary: Update room availability by ID.
      operationId: updateRoomAvailabilityById
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the room to update availability.
          schema:
            type: string
      requestBody:
        description: Updated availability object.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dates:
                  type: array
                  items:
                    type: string
                    format: date
              required:
                - dates
      responses:
        200:
          description: Room availability has been updated.
        400:
          description: Bad request.
        401:
          description: Unauthorized
        404:
          description: Room not found
  /api/users/{id}:
    put:
      tags:
        - "users"
      summary: Update a user by ID.
      operationId: updateUserById
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the user to be updated.
          schema:
            type: string
      requestBody:
        description: Updated user object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Successfully updated user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad request.
        401:
          description: Unauthorized
        404:
          description: User not found

    delete:
      tags:
        - "users"
      summary: Delete a user by ID.
      operationId: deleteUserById
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the user to be deleted.
          schema:
            type: string
      responses:
        200:
          description: User has been deleted.
        401:
          description: Unauthorized
        404:
          description: User not found
    get:
      tags:
        - "users"
      summary: Get a user by ID.
      operationId: getUserById
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the user to be retrieved.
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
        404:
          description: User not found

  /api/users:
    get:
      tags:
        - "users"
      summary: Get all users.
      operationId: getAllUsers
      responses:
        200:
          description: Successfully retrieved all users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
components:
  schemas:
    Room:
      type: object
      properties:
        title:
          type: string
          description: The title of the room.
        price:
          type: number
          description: The price of the room.
        maxPeople:
          type: number
          description: The maximum number of people the room can accommodate.
        desc:
          type: string
          description: The description of the room.
        roomNumbers:
          type: array
          description: List of room numbers with their unavailable dates.
          items:
            type: object
            properties:
              number:
                type: number
                description: The room number.
              unavailableDates:
                type: array
                items:
                  type: string
                  format: date
                description: List of dates when the room is unavailable.

    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        isAdmin:
          type: boolean
      required:
        - username
        - email
        - password
